### ISSUE TITLE
Incompatibility with Immersive Lighting

### ISSUE THREAD

**Issue by WittyWhiscash** [paulevsGitch/SkyWorld#2]
Cheers!
I am the dev of Immersive Lighting. One of my users has reported a server crash while trying to load both your mod and my mod in their environment.

The issue can be found here: https://github.com/WittyWhiscash/Immersive-Lighting/issues/3

The user's crash log can be found here: https://pastebin.com/mVQDtgT3

The user reports using Minecraft version 1.15.2, the latest Fabric Loader (they used Fabric Installer), and mod version 0.3.0-pre-release.

**Comment by paulevsGitch** [comment]
Thanks, I will look at it. It is probably an issue with ButtonWidget, I will move it to client side.

**Comment by paulevsGitch** [comment]
Fixed
