### ISSUE TITLE
[bug] Biomes don't seem to generate correctly

### ISSUE THREAD

**Issue by Aero48** [paulevsGitch/SkyWorld#3]
While it appears as though the islands generate with their own biomes, the trees/foliage seems to be stuck on one biome for all of the islands.

![image](https://user-images.githubusercontent.com/56200404/84468663-637fca80-ac4d-11ea-9d39-0d4b24637a45.png)

![image](https://user-images.githubusercontent.com/56200404/84468672-67abe800-ac4d-11ea-9980-19c551575371.png)

For example, all of the islands in this world seem to generate the foliage of a plains biome despite each island displaying different biomes in the F2 menu.

**Comment by paulevsGitch** [comment]
I couldn't recreate you bug, what version do you use and with what generator options?

**Comment by Aero48** [comment]
> I couldn't recreate you bug, what version do you use and with what generator options?

0.3.1 with default generator options.

**Comment by paulevsGitch** [comment]
With old API it worked, with new one looks like not. I will make an update soon.

**Comment by paulevsGitch** [comment]
I fixed this error, now everything should be ok
